version: '3'
services:
  tmserver:
    image: toprock/tmserver:latest
    volumes:
      - ./GameData/Profiles:/opt/tmserver/GameData/Profiles
      - ./GameData/Scores:/opt/tmserver/GameData/Scores
      - ./GameData/Tracks/MatchSettings/:/opt/tmserver/GameData/Tracks/MatchSettings/
    environment:
      SERVER_NAME: My server # if you want colours be warned that $ needs to be escaped by $ in Docker
      SERVER_DESC: Let's race
      SERVER_SA_PASSWORD: SuperAdmin
      SERVER_ADM_PASSWORD: Admin
    ports:
      - 2350:2350
      - 3450:3450
      - 3450:3450/udp
  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: aseco
      MYSQL_USER: tmf
      MYSQL_PASSWORD: tmfpass
  xaseco:
    image: toprock/tmserver:xaseco
    depends_on:
      - "tmserver"
      - "mysql"
    environment:
      MYSQL_SERVER: 'mysql' #name like the service 
      MYSQL_LOGIN: tmf # same as MYSQL_USER
      MYSQL_PASSWORD: tmfpass # same as MYSQL_PASSWORD
      ASECO_MASTER_ADMIN: YOUR_TMF_LOGIN_TM #Online account name for TMNF, wont work for offline accounts
      ASECO_ADMIN: ADMIN_User_Login_TM #Online account name for TMNF, wont work for offline accounts
      SERVER_SA_PASSWORD: SuperAdmin # SA Password configured in tmserver
      SERVER_IP: tmserver #Set this to the service / hostname of timserver