version: '3'
services:
  tmserver:
    image: toprock/tmserver:latest
    volumes:
      - ./GameData/Profiles:/opt/tmserver/GameData/Profiles
      - ./GameData/Scores:/opt/tmserver/GameData/Scores
      - ./GameData/Tracks/MatchSettings/:/opt/tmserver/GameData/Tracks/MatchSettings/
    environment:
      SERVER_NAME: My server # if you want colours be warned that $ needs to be escaped by $ in Docker
      SERVER_DESC: Let's race
    ports:
      - 2350:2350
      - 3450:3450
      - 3450:3450/udp
  mysql:
    image: mysql:5.5
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: aseco
      MYSQL_USER: tmf
      MYSQL_PASSWORD: tmfpass
  xaseco:
    image: xaseco:latest
    depends_on:
      - "tmserver"
      - "mysql"
    environment:
      MYSQL_SERVER: 'mysql'
      MYSQL_LOGIN: tmf
      MYSQL_PASSWORD: tmfpass
      ASECO_MASTER_ADMIN: YOUR_TMF_LOGIN
      SERVER_SA_PASSWORD: SuperAdmin